# Generated by Django 4.1.7 on 2023-04-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='files')),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
